name: turn_digital
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  adaptive_screen_utils: ^2.4.0
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_local_notifications: ^18.0.1
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  fluttertoast: ^8.2.12
  freezed: ^3.0.3
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  hive: ^2.2.3
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  mockito: ^5.4.5
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.2.1
  timezone: ^0.10.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Airbnb Cereal App
      fonts:
        - asset: assets/fonts/AirbnbCereal_W_Bd.otf
        - asset: assets/fonts/AirbnbCereal_W_Bk.otf
        - asset: assets/fonts/AirbnbCereal_W_Lt.otf
        - asset: assets/fonts/AirbnbCereal_W_Blk.otf
        - asset: assets/fonts/AirbnbCereal_W_Md.otf
        - asset: assets/fonts/AirbnbCereal_W_XBd.otf

  assets:
    - assets/images/
