name: turn_digital
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  adaptive_screen_utils: ^2.4.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Airbnb Cereal App
      fonts:
        - asset: assets/fonts/AirbnbCereal_W_Bd.otf
        - asset: assets/fonts/AirbnbCereal_W_Bk.otf
        - asset: assets/fonts/AirbnbCereal_W_Lt.otf
        - asset: assets/fonts/AirbnbCereal_W_Blk.otf
        - asset: assets/fonts/AirbnbCereal_W_Md.otf
        - asset: assets/fonts/AirbnbCereal_W_XBd.otf

  assets:
    - assets/images/
